services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/ragdb
      NODE_ENV: development
      PORT: 3000
      OCR_SERVICE_URL: flask-ocr:5000
    depends_on:
      - db

  flask-ocr:
    build:
      context: ./ocr-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - ./ocr-service:/app

volumes:
  pgdata:
